### ISSUE TITLE
Not working on openSUSE-Leap-42.1 gnome v3.16.2

### ISSUE THREAD

**Issue by techno2088** [omid/Hijri-Calendar-for-Gnome-Shell#1]
hi,
i've installed the extension as in the instructions in README.md
i use openSUSE-Leap-42.1 gnome v3.16.2.

however it seems that the gnome version i have is outdated(old) or your extension isn't updated..
Gnome isn't telling me which is which !!!!
it just says "extension doesn't support shell version"
any way would you please put a minimume version in your README.md file ??

**Comment by omid** [comment]
Hi,

Sorry for my late response.

I don't have any environment to test it on older versions of Gnome. So I tested this calendar on the latest versions and currently it is 3.20.

But you can change supported versions of gnome in metadata.json file and check if extension is working or not.

After adding 3.16 and 3.18 to metadata.json, it should looks like:

```
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Shows Hijri date in the top panel.",
  "name": "Hijri Calendar",
  "original-authors": "Omid Mottaghi Rad",
  "shell-version": [
    "3.16",
    "3.18",
    "3.20"
  ],
  "url": "https://github.com/omid/Hijri-Calendar-for-Gnome-Shell",
  "uuid": "HijriCalendar@oxygenws.com",
  "version": 1
}
```

Regards.

**Comment by techno2088** [comment]
yes it works just fine
