### ISSUE TITLE
Support for GNOME 42.5

### ISSUE THREAD

**Issue by shakram02** [omid/Hijri-Calendar-for-Gnome-Shell#18]
Is there plans to upgrade the extension for GNOME v42.5? If not, can you please provide some guidance on how this can be done?

Thanks,

**Comment by omid** [comment]
Hey @shakram02 

I don't really support this extension anymore, but check and accept PRs and release a new version.

But there is another extension for Persian Calendar, which you can find here: https://github.com/omid/Persian-Calendar-for-Gnome-Shell

The two source codes are really diverged at this point of time.

I see two ways to do so.
1. Find the commits these two source codes started to diverged and apply whatever there, here also.
2. Add the functionality to the other one, to be able to choose the default calendar (+ Arabic language to choose) you can find [the ticket here](https://github.com/omid/Persian-Calendar-for-Gnome-Shell/issues/57) (it's in Persian)

I suggest the second one.

More about the other calendar. It already supports Gregorian, Hijri and Persian calendars and can show all at the same time. But the main calendar is ALWAYS the Persian one (https://github.com/omid/Persian-Calendar-for-Gnome-Shell/blob/master/PersianCalendar%40oxygenws.com/Calendar.js)

It can have an option in settings to choose the default calendar.

**Comment by shakram02** [comment]
Thanks a lot Omid for the very detailed answer
