### ISSUE TITLE
Gnome notification on unlock

### ISSUE THREAD

**Issue by e-inquirer** [omid/Hijri-Calendar-for-Gnome-Shell#5]
Every time the user unlocks their system, Gnome Shell presents a pop-up notification from Hijri-Calendar.

![screenshot from 2017-04-02 22-47-42](https://cloud.githubusercontent.com/assets/18729130/24593996/860291da-17f6-11e7-9376-0b07eb076555.png)

**Comment by omid** [comment]
Yes, you are right. I put notification functionality in "enable" function of gnome-shell... and gnome-shell will call it when you login, unlock, restart gnome-shell, install this extension and maybe some other places!
So it's normal behavior of the extension.

But it's a good idea to add an option in settings to disable this functionality :-)

**Comment by e-inquirer** [comment]
Is it possible to disable this functionality through `dconf Editor`, and if so how?

**Comment by omid** [comment]
No, maybe a new checkbox in Preferences of the extension is fine, is it?

**Comment by e-inquirer** [comment]
Yeah, that'd be perfect!

**Comment by e-inquirer** [comment]
Thank you.
