### ISSUE TITLE
Change calendar position

### ISSUE THREAD

**Issue by mnop23** [omid/Hijri-Calendar-for-Gnome-Shell#6]
Can you make check box in Preferences to change position (Centre or Left) ? 
I think it would be nice if hijri calendar can replace main calendar of gnome.

**Comment by omid** [comment]
Yes, you are right, it's a long-lasting feature request, but I didn't have enough time to do this. (You can find it [here](https://github.com/omid/Persian-Calendar-for-Gnome-Shell/commit/0cb3defa3bc422df4227ba8b6a684e22a8007609))

And the "replacement with default calendar" might be another option or another extension at all 😄
For example, personally, I like to have both calendars.

If you can help yourself and I, create a fork and make a pull request
